import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className="w-full p-4">
          <nav className=" bg-gray-800 w-full p-4 text-white  rounded-md ">
            <div className="flex items-center justify-between">
              <h1 className="text-2xl font-bold">
                <Link href="/">
                Mem Nastik
                </Link></h1>
              <div className="flex space-x-4">
                <Link href="/chuck" className="hover:text-gray-300">
                  Chuck Norris Joke
                </Link>
                <Link href="/joke" className="hover:text-gray-300">
                  Random Joke
                </Link>
              </div>
            </div>
          </nav>
        </div>

        {children}
      </body>
    </html>
  )
}
