import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <nav className="bg-gray-800 m-4 p-4 text-white  rounded-md">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-bold">Mem Generator</h1>
            <div className="flex space-x-4">
              <Link href="/chuck" className="hover:text-gray-300">
                Chuck Norris Joke
              </Link>
              <Link href="/joke" className="hover:text-gray-300">
                Random Joke
              </Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
